# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=256)),
                ('max_running_task', models.SmallIntegerField(default=2)),
                ('count_running_task', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('exec_time', models.CharField(max_length=256, null=True)),
                ('status', models.SmallIntegerField(choices=[(8, 'Completed'), (2, 'In Queue'), (4, 'Run')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdline', models.CharField(default='python {0}/test.py', max_length=256)),
                ('pid', models.SmallIntegerField(null=True)),
                ('ret_code', models.SmallIntegerField(null=True)),
                ('run_timeout', models.SmallIntegerField(default=3600)),
                ('done', models.BooleanField(default=False)),
                ('was_run', models.BooleanField(default=False)),
                ('node', models.CharField(max_length=256)),
                ('upstream', models.CharField(max_length=256, null=True)),
                ('sched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Scheduler')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
    ]
